export const DEBUG_AUTH_FLAG = "VITE_DEBUG_AUTH";
export const DEBUG_POST_EDIT = "VITE_DEBUG_POST_EDIT";
export const ENABLE_POST_RENAME = "VITE_ENABLE_POST_RENAME";
export const ENABLE_MOCK_DATA = "VITE_ENABLE_MOCK_DATA";
